### ISSUE TITLE
Problèmes de rétro-compatibilité

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/joy2learn-bonnesnotes#2]
### OS Mojave and Safari version 14.1.2

- [x] On every page, there is still a large blank space at the bottom of the page where the partner logos should be:

![image](https://user-images.githubusercontent.com/2088968/210559184-4f09d4f3-a612-4ac5-8779-bb8e0bc3cd3a.png)

- [x] Under “Notre Projet”, I am still seeing the same issue as before with large blank spaces under “Quelques Images”:

![image](https://user-images.githubusercontent.com/2088968/210559241-53c15653-4ef6-4896-8b26-8a8450c48876.png)

- [x] ...and also between each line of photographs:

![image](https://user-images.githubusercontent.com/2088968/210559296-15a18853-b4bc-41b2-afd8-99b9cb10d8c2.png)

- [x] Under “Repère d’équite”, the video at the very end is cut off, even if I try to scroll up/ down:

![image](https://user-images.githubusercontent.com/2088968/210559371-95a6efcb-3e3f-48d0-8c2e-3ba12e629dd1.png)

- [x] I still don’t see the pictures under “Actualités” on my mac, still only the headlines:

![image](https://user-images.githubusercontent.com/2088968/210559438-5cd63527-c9be-4661-9e3e-f39c29ade4e5.png)

### Firefox version 108.0.1

- [x] slight image misalignment with Firefox under “Notre Projet”

![image](https://user-images.githubusercontent.com/2088968/210559591-bd386637-f076-4ddd-abb5-6f199b3f2eb1.png)

**Comment by alexisben** [comment]
![image](https://user-images.githubusercontent.com/4630530/211333717-91f3dbb0-755b-470d-8c7b-eeb7c04efedf.png)

Problème d'alignement des flèches

**Comment by alexisben** [comment]
@arnaudlevy peux-tu demander un re-test à Baldeesh ? Merci !
